env:
  browser: true
  es6: true
  commonjs: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  prefer-const:
    - error
    - destructuring: all
      ignoreReadBeforeAssign: false
  no-unused-vars:
    - error
    - argsIgnorePattern: "^_"
  comma-dangle:
    - error
    - arrays: 'only-multiline'
      objects: 'only-multiline'
      exports: 'only-multiline'
globals:
  module: false
  process: false
  _: false
  ActionCable: false
