AllCops:
  TargetRubyVersion: 2.5.1
  TargetRailsVersion: 5.2
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'node_modules/**/*'
    - 'bin/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Layout/IndentationConsistency:
  EnforcedStyle: rails
