require:
  - rubocop-rails
  - rubocop-rspec
AllCops:
  NewCops: enable
  # Exclude:
  #   - 'db/migrate/*'
  #   - 'node_modules/**/*'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

# Metrics/BlockLength:
#   Enabled: false

# Layout/IndentationConsistency:
#   EnforcedStyle: indented_internal_methods

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/TrailingCommaInArguments:
  Enabled: false
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/AsciiComments:
  Enabled: false
