# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0386e218598704eede122aeaef0f41b52470251c3fecf24b5baee70f18dbfaa4443f10e0c9d3b521ee2c46547ec078654eac9ff2a0e979d39f83218be7e76539

test:
  secret_key_base: 210937ee7cc9325a71ee0150934a02a3bba8faa38c07d34392d5eab699c76cba1b9a4a234e7f1277007f750c46724f2c99ec4dd791380600c6d110d225a8968f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
